#api for listing all doctors 

###
GET http://127.0.0.1:8000/doctors/
Accept: application/json

#api for adding doctors 

###
POST http://127.0.0.1:8000/doctors/
Content-Type: application/json

{
    "name": "Fathima Rahman",
    "specialization": "gynecology",
    "fee": 900,
    "qualification": "mbbs, ms",
    "email": "fathimarahman@gmail.com"
}

#api call for retrieving a doctor

###
GET http://127.0.0.1:8000/doctors/3/
Accept: application/json

#api call for retrieving a doctor
###
PUT  http://127.0.0.1:8000/doctors/3/
Content-Type: application/json

{
    "name": "Navami PM",
    "specialization": "gynecology",
    "fee": 100,
    "qualification": "mbbs",
    "email": "navamipashu@gmail.com"    
}

#api call for deleting a doctor

###
DELETE  http://127.0.0.1:8000/doctors/2/
Accept: application/json


#v2 endpointss
#APi endpoint for listing all 
###

GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json
Authorization: Basic Admin:admin@123
#creating a records
###
POST http://127.0.0.1:8000/v2/doctors/
Content-Type: application/json

{
    "name": "hanaaaa",
    "specialization": "gynecology",
    "fee": 900,
    "qualification": "mbbs, ms",
    "email": "aajndhjdm@gmail.com",
    
}

#api call for retrieving a doctor

###
GET http://127.0.0.1:8000/v2/doctors/1/
Accept: application/json

#api call for deleting a doctor

###
DELETE  http://127.0.0.1:8000/v2/doctors/6/
Accept: application/json


#updating a record  
###
put http://127.0.0.1:8000/v2/doctors/3/
Content-Type: application/json

{
    "id": 3,
    "name": "Navami PM",
    "specialization": "gynecology",
    "fee": 400,
    "qualification": "mbbs md",
    "email": "navamipashu@gmail.com"
  }

  #api call for admin Register 
###
POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{

    "username":"Admin",
    "email":"admin123@gmail.com",
    "password":"admin@123"
}

