#api for listing all doctors 

###
GET http://127.0.0.1:8000/doctors/
Accept: application/json

#api for adding doctors 

###
POST http://127.0.0.1:8000/doctors/
Content-Type: application/json

{
    "name": "Fathima Rahman",
    "specialization": "gynecology",
    "fee": 900,
    "qualification": "mbbs, ms",
    "email": "fathimarahman@gmail.com"
}

#api call for retrieving a doctor

###
GET http://127.0.0.1:8000/doctors/3/
Accept: application/json

#api call for retrieving a doctor
###
PUT  http://127.0.0.1:8000/doctors/3/
Content-Type: application/json

{
    "name": "Navami PM",
    "specialization": "gynecology",
    "fee": 100,
    "qualification": "mbbs",
    "email": "navamipashu@gmail.com"    
}

#api call for deleting a doctor

###
DELETE  http://127.0.0.1:8000/doctors/2/
Accept: application/json


#v2 endpointss
#APi endpoint for listing all 
###

GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json
Authorization: Basic Admin:admin@123
#creating a records
###
POST http://127.0.0.1:8000/v2/doctors/
Content-Type: application/json
Authorization: Basic Admin:admin@123

{
    "name": "hanaaaa",
    "specialization": "gynecology",
    "fee": 900,
    "qualification": "mbbs, ms",
    "email": "aajndhjdm@gmail.com",
    
}

#api call for retrieving a doctor

###
GET http://127.0.0.1:8000/v2/doctors/1/
Accept: application/json
Authorization: Basic Admin:admin@123
#api call for deleting a doctor

###
DELETE  http://127.0.0.1:8000/v2/doctors/6/
Accept: application/json
Authorization: Basic Admin:admin@123

#updating a record  
###
put http://127.0.0.1:8000/v2/doctors/3/
Content-Type: application/json
Authorization: Basic Admin:admin@123

{
    "id": 3,
    "name": "Navami PM",
    "specialization": "gynecology",
    "fee": 400,
    "qualification": "mbbs md",
    "email": "navamipashu@gmail.com"
  }

  #api call for admin Register 
###
POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{

    "username":"Admin",
    "email":"admin123@gmail.com",
    "password":"admin@123"
}

#api call for listing all appointments
###
GET http://127.0.0.1:8000/appointments/
Accept: application/json

###
POST http://127.0.0.1:8000/appointments/
Content-Type: application/json

{
    "patient_name":"Aliya Sherin",
    "phone":"9872345577",
    "doctor":1,
    "appointment_date":"2026-10-11",
    "problem":"cough"
}

#api call for signup user
###
POST http://127.0.0.1:8000/v2/bookings/signup/
Content-Type: application/json

{

    "username":"user1",
    "email":"user123@gmail.com",
    "password":"user@123"
}

## api call for v2========



#api for lising all appointments
###
GET http://127.0.0.1:8000/v2/bookings/appointments/
Accept: application/json
Authorization: Basic user1:user@123

#api call for creating appointments
###
POST http://127.0.0.1:8000/v2/bookings/appointments/
Content-Type: application/json
Authorization: Basic user1:user@123

{
    "patient_name":"hansiya",
    "phone":"6245894123",
    "doctor":5,
    "appointment_date":"2026-10-11",
    "problem":"vomitting"
}


#api call for retrieving a appointment 
###
GET http://127.0.0.1:8000/v2/bookings/appointments/5
Accept: application/json
Authorization: Basic user1:user@123

# api call for updating an appointment

###
PUT  http://127.0.0.1:8000/v2/bookings/appointments/9/
Content-Type: application/json
Authorization: Basic user1:user@123

{
    "patient_name":"hiba shahseey  ",
    "phone":"9875894123",
    "doctor":1,
    "appointment_date":"2026-10-11",
    "problem":"vomitting"
}

#api for deleting an appointment

### 
DELETE  http://127.0.0.1:8000/v2/bookings/appointments/12/
Accept: application/json
Authorization: Basic user1:user@123